version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        volumes:
            - .:/app
        ports:
            - '3001:3001'
        environment:
            NODE_ENV: development
