version: "3.1"

services:
  db:
    build: .docker
    container_name: db
    environment:
      - POSTGRES_PASSWORD=indt@2024
      - POSTGRES_USER=indt
      - POSTGRES_DB=db_access_control_system
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-indt
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8005:80"
    depends_on:
      - db
